services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: postgrespw
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  search-service:
    image: ${DOCKER_USERNAME}/search-service:latest
    container_name: search_service_container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - DB_NAME=SearchServiceDb
      - ASCII_SERVICE_URL=http://ascii-service/api/v1
      - RABBIT_MQ_HOST=rabbitmq
    ports:
      - 5102:80
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ./postgres_data
      o: bind
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      device: ./mongodb_data
      o: bind
